name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📥 Install dependencies
        run: npm install

      - name: ⚙️ Run Cypress tests
        run: npx cypress run

      - name: 📤 Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: 📤 Upload videos on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos